import Link from 'next/link'
import Head from 'next/head'
import dbConnect from '../../lib/dbConnect'
import Movie from '../../models/Movie'
import { IMovie } from '../interface/IMovie'

interface IProps {
    movies: IMovie[]
}

export default function Home({ movies }: IProps) {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main className='container'>
                <h1 className='text-center'>Movie</h1>
                <Link href='/new-movie'>
                    <a className='btn btn-primary w-100 mb-2'> Add movie</a>
                </Link>
                {movies.map(({ _id, title, plot }) => (
                    <div className='card mb-2' key={_id}>
                        <div className='card-body'>
                            <div className='h5 text-uppercase'>{title}</div>
                            <p className='fw-light'>{plot}</p>
                            <Link href={`/${_id}`}>
                                <a className='btn btn-success btn-sm me-2'>
                                    Detail
                                </a>
                            </Link>
                        </div>
                    </div>
                ))}
            </main>
        </div>
    )
}

export async function getServerSideProps() {
    try {
        await dbConnect()
        const result = await Movie.find({})
        const movies = result.map((doc) => {
            const movie = doc.toObject()
            movie._id = movie._id.toString()
            return movie
        })
        return { props: { movies } }
    } catch (error) {
        console.log(error)
    }
}
